name: Tear Down Azure Automated Hacker Trap 💣

on:
  workflow_dispatch:

jobs:
  terraform-destroy:
    runs-on: ubuntu-latest
    steps:
    - name: Open Code Box
      uses: actions/checkout@v4

    - name: Setup Terraform Robot
      uses: hashicorp/setup-terraform@v3

    - name: Destroy Trap in Azure
      env:
        ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
        ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      run: |
        cd terraform
        terraform init
        terraform destroy -auto-approve
